### ISSUE TITLE
Using Multiplayer input makes InputMouseMotions no longer activate _unhandled_input() and _input()

### ISSUE THREAD

**Issue by Purplooo** [matjlars/godot-multiplayer-input#10]
I use a script that uses InputMouseMotions to rotate my camera, whenever i use MultiplayerInput InputMouseMotion Doesn't call from _input() or _unhandledinput().

**Comment by matjlars** [comment]
I can't think of how it could be related. MultiplayerInput basically just copies your existing input actions, it doesn't intercept events or anything like that. Can you try using Godot's Control debugger? While the game is running, click the mouse button anywhere, then navigate to the Debugger tab at the bottom, then navigate to the Misc tab to see the last Control node clicked. Sometimes this helps me figure out why input events are not firing like I expect. If that is not it, can you post a pastebin of your script with your input function so I can have a gander there?

**Comment by Purplooo** [comment]
I discovered about 3 minutes after posting this that the issue was something entirely unrelated to multiplayer input.

My bad

**Comment by matjlars** [comment]
No problem!  Have a wonderful day and thanks for using my multiplayer input thingy :)

**Comment by steveweenie** [comment]
> I can't think of how it could be related. MultiplayerInput basically just copies your existing input actions, it doesn't intercept events or anything like that. Can you try using Godot's Control debugger? While the game is running, click the mouse button anywhere, then navigate to the Debugger tab at the bottom, then navigate to the Misc tab to see the last Control node clicked. Sometimes this helps me figure out why input events are not firing like I expect. If that is not it, can you post a pastebin of your script with your input function so I can have a gander there?

Thank god you mentioned this!! Just fixed an issue that made me wanna pull my hair out lol. You learn something everyday
