### ISSUE TITLE
deserialize_inputs_for_actions() shows two erros upon game initialization for each action

### ISSUE THREAD

**Issue by ralke1** [matjlars/godot-multiplayer-input#9]
Hello!
I have simple actions for keyboard and gamepad. (sorry for my godot in PT_BR)
![image](https://github.com/user-attachments/assets/7c6a9295-3f53-4b73-9f57-9c4fc8bc2d47)

when starting the game, it throws the following 2 errors for each action:
input_helper.gd:230 @ deserialize_inputs_for_actions(): The InputMap action "0Action" doesn't exist. Did you mean "Action"?
input_helper.gd:261 @ deserialize_inputs_for_actions(): The InputMap action "0Action" doesn't exist. Did you mean "Action"?

![image](https://github.com/user-attachments/assets/d25dabe5-a6b5-4083-8b2e-1194a9a74368)

does anyone have any suggestions or quickfixes for it?

btw: really cool addon, thank for the great work!

**Comment by matjlars** [comment]
Hi ralke1, sorry I didn't see this until just now, I've been swamped. I see you closed the issue but I just wanted to make sure you got it figured out. If you still have an issue, could you post a pastebin of your input_helper.gd script please? Thank you and I hope you have a great day!
